# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
    - 'myhtml/**'
    - 'Makefile'
    - 'CMakeLists.txt'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths: 
    - 'src/**'
    - 'myhtml/**'
    - 'Makefile'
    - 'CMakeLists.txt'
    - '.github/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # apt-get update
    - name: Update
      run: sudo apt-get update

    # Install deps
    - name: Install libcurl
      run: sudo apt-get install -y libcurl4-openssl-dev
      
    - name: Install libidn2-dev
      run: sudo apt-get install -y libidn2-0 libidn2-0-dev

    # Runs a single command using the runners shell
    - name: Checkout myhtml
      run: |
        git submodule init
        git submodule update --checkout

    # Runs a set of commands using the runners shell
    - name: CMake build
      run: |
        rm -rf build
        cmake -S . -B build -D WITH_IDN2=ON
        cmake --build build/
