name: build

on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
    - 'myhtml/**'
    - 'Makefile'
    - 'CMakeLists.txt'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths: 
    - 'src/**'
    - 'myhtml/**'
    - 'Makefile'
    - 'CMakeLists.txt'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update
      run: sudo apt-get update

    - name: Install libcurl
      run: sudo apt-get install -y libcurl4-openssl-dev
      
    - name: Install libidn2-dev
      run: sudo apt-get install -y libidn2-0 libidn2-0-dev

    - name: Checkout myhtml
      run: |
        git submodule init
        git submodule update --checkout

    - name: CMake build
      run: |
        rm -rf build
        cmake -S . -B build -D WITH_IDN2=ON
        cmake --build build/
